name: JOY挂机

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0/2 * * *"
        - cron: "40 0/2 * * *"
        - cron: "20 1,3,5,7,9,11,13,15,17,19,21,23 * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【JOY挂机】"
              run: |
                  node jd_crazy_joy_coin.js
              env:
                  JD_COOKIE: ${{ secrets.JD_COOKIE }}
                  TG_BOT_TOKEN: ${{ github.event.client_payload.TG_BOT_TOKEN || secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ github.event.client_payload.TG_USER_ID || secrets.TG_USER_ID }}
